name: Build and run unittest with Intel oneAPI
on:
  push:
  pull_request:

# oneapi install adapted from the build_linux_apt_cpp of
# https://github.com/oneapi-src/oneapi-ci/blob/master/.github/workflows/build_all.yml

env:
  LINUX_CPP_COMPONENTS: intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic_intel-oneapi-mkl_intel-oneapi-mkl-devel_intel-oneapi-mpi_intel-oneapi-mpi-devel

jobs:
  build_and_unittest_oneapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Intel oneAPI apt repo
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/oneAPI.list" -o APT::Get::List-Cleanup="0"
      - name: Collect apt dependencies
        run: |
          echo "$LINUX_CPP_COMPONENTS" | sed "s/_/ /g" | xargs -n 1 apt-cache depends | tee depends.txt
      - name: Cache install
        id: cache-install
        uses: actions/cache@v3
        with:
          path: /opt/intel/oneapi/
          key: install-${{ env.LINUX_CPP_COMPONENTS }}-${{ hashFiles('**/depends.txt') }}
      - name: Install tools including oneAPI
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y $(echo "$LINUX_CPP_COMPONENTS" | sed "s/_/ /g")
          echo "Size of /opt/intel/oneapi/"
          du -csh /opt/intel/oneapi
      - name: Install build and runtime python dependency
        run: sudo apt-get install -y build-essential cmake python3-scipy
      - name: Build LibRPA without LibRI
        run: |
          source /opt/intel/oneapi/setvars.sh
          CXX=mpiicpc cmake -DUSE_CMAKE_INC=OFF -DUSE_LIBRI=OFF -B build -DENABLE_TEST=ON
          cmake --build build -j2
      - name: Run unittests, display log
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake --build build --target test
          cat build/Testing/Temporary/LastTest.log
